name: CI

permissions:
  contents: read

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    paths:
      - 'astro-portfolio/**'
      - '.github/workflows/ci.yml'
  workflow_call:

jobs:
  build:
    name: Code standards & build
    runs-on: ubuntu-latest
    timeout-minutes: 3
    defaults:
      run:
        working-directory: astro-portfolio

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: "â˜ï¸ Checkout repository"
        uses: actions/checkout@v4
        
      - name: Enable Corepack for Yarn 4
        run: corepack enable

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: astro-portfolio/yarn.lock

      - name: "ğŸ“¦ Install dependencies"
        run: yarn install --frozen-lockfile

      - name: "ğŸ–¥ï¸ Install Playwright dependencies on Ubuntu"
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-4-1 libgraphene-1.0-0 libwoff2-1 libvpx9 libevent-2.1-7 \
            libopus0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
            libflite1 libavif16 libharfbuzz-icu0 libsecret-1-0 libhyphen0 \
            libmanette-0.2-0 libgles2-mesa libx264-163

      - name: "ğŸŒ Install Chromium browser for Playwright"
        run: yarn playwright install chromium

      - name: "ğŸ” Lint code"
        run: yarn lint

      - name: "ğŸ“ Checking code format"
        run: yarn format:check

      - name: "ğŸš€ Build the project"
        run: yarn build
